// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function IsListening():Promise<boolean>;

export function LoadModel(arg1:string):Promise<void>;

export function Shutdown():Promise<void>;

export function StartDictation():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopDictation():Promise<void>;
