// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsListening() {
  return window['go']['speech']['SpeechService']['IsListening']();
}

export function LoadModel(arg1) {
  return window['go']['speech']['SpeechService']['LoadModel'](arg1);
}

export function Shutdown() {
  return window['go']['speech']['SpeechService']['Shutdown']();
}

export function StartDictation() {
  return window['go']['speech']['SpeechService']['StartDictation']();
}

export function Startup(arg1) {
  return window['go']['speech']['SpeechService']['Startup'](arg1);
}

export function StopDictation() {
  return window['go']['speech']['SpeechService']['StopDictation']();
}
