// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DetectShape(arg1:Array<Record<string, number>>):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function StartRecording():Promise<string>;

export function StopRecording():Promise<string>;

export function UploadLesson(arg1:string,arg2:string):Promise<string>;
